version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres-15
    environment:
      POSTGRES_DB: otus-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db-network
    volumes:
      - pgadmin_data:/data/pgadmin
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    # command: start       # production mode
    command: start-dev # development mode
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-15/otus-db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  pgadmin_data:
